### ISSUE TITLE
Combat Power Calculation Update

### ISSUE THREAD

**Issue by Xeio** [joakibj/tswcalc#35]
I'm just going to preliminarily open an issue for this, but the Combat Power calculation has been updated on Test Live.

I've been doing some of the math work on this on the Test Live forums, but it's not really complete. The current formula is mostly accurate up to around 5200 Attack Rating, but above that the newer formula kicks in.

**Comment by joakibj** [comment]
Math is not really my thing, I am of no help here. 

For reference, this is the source I used for the CP calculation in the first place: https://sites.google.com/site/tswnotes/math
