### ISSUE TITLE
Woodcutter item's

### ISSUE THREAD

**Issue by Inkraja** [joakibj/tswcalc#38]
![woodcutters](https://cloud.githubusercontent.com/assets/10184036/10869341/3d7aee26-80ad-11e5-8c95-b2b6338f8d8d.png)
Hey, i think it would be helpful to add the Items (like NYR), item id's are:
9135141
9135178
9135212

Contact me, if u need more Infos about

**Comment by joakibj** [comment]
@Inkraja , I added support for this in the newest version, 1.8.0 and deployed to the site. Let me know if stats / text have changed since you reported this.

**Comment by Inkraja** [comment]
yes it does, i will make a PR for the changes.

**Comment by Xeio** [comment]
Just gonna say checkboxes are gonna be interesting if anyone ever actually manages to start downing the NM raids.

There's something like a dozen our so new items spread out over the slots that have been data mined, plus the 10.9 NY variants.

But it doesn't seem like that will be anytime soon so...

**Comment by Inkraja** [comment]
I push a lot of Item Information in this commit: https://github.com/Inkraja/game-tsw/commit/8e4b399f512507d8a67892406181aa7119501404

I only have an idea which item  can be dropped in which nm, but its just speculation because the names give some hints. i only added the english ones.
Xeio dont give up, the new update will change all *soon* :smile:

**Comment by joakibj** [comment]
@Xeio , yeah true. That current UI doesn't support fixed drops that well. I am surprised that tswcalc has been relevant for endgame still after 2.5 years. The technical debt and design decisions of days gone by have started showing their ugly heads :)
