### ISSUE TITLE
New Critical Chance % formula

### ISSUE THREAD

**Issue by joakibj** [joakibj/tswcalc#39]
New critchance in TSW 1.12.6

https://forums.thesecretworld.com/showthread.php?94350-The-new-crit-rating&p=1976975&viewfull=1#post1976975

Old formula:
39 - 68 / ( EXP( critical rating / 787.6 ) + 1 )

New formula:
55.14 - 100.3 / ( EXP( critical rating / 790.3 ) + 1 )

**Comment by Inkraja** [comment]
The AR is also changed, i only found the post on TL forum but i have o idea whats the new AR formular:
https://forums-tl.thesecretworld.com/showthread.php?18310-Diminishing-returns-formula-not-really-changed
