### ISSUE TITLE
Issue 13 (Shambala) Signet Support

### ISSUE THREAD

**Issue by Xeio** [joakibj/tswcalc#47]
Opening issue to track this until someone has time to add them to the data files.

Spreadsheet from @Inkraja: https://docs.google.com/spreadsheets/d/11AOygXcnzmZHr9bdLmntGEUgCZWA9t5EdKGZYzYuNns/edit?usp=sharing

We may want to verify these are still accurate as of Live yesterday too.

**Comment by joakibj** [comment]
Yeah looks like this is all about punching data to: https://github.com/joakibj/tswcalc/blob/develop/src/javascript/data/tswcalc-data-signets.js . Only issue is icons, which imo should just show a decent placeholder.

**Comment by Inkraja** [comment]
check this out: https://github.com/Inkraja/tswcalc/commit/9e29492ddb1183a19c5005793d8033cbb0213654

there are 3 /*!!*/ there are open question because the heal is based on the heal raiting, but i didnt know the formular for it. And one is for the Coup de Grâce Signet....

**Comment by Xeio** [comment]
I'll just note though this was already in TS:

* Coup de Grâce name is fine
* Don't use signet IDs 80-93
* Move the signets to the exsiting 'major', 'minor', ect lists
* Possibly use something like "shambala: true" rather than "requires: 'issue-14'", requires is coded to be used for the Venice vendor items specifically, so probably best to avoid that code running for these
