### ISSUE TITLE
Future non-custom item support (NM Raid drops)

### ISSUE THREAD

**Issue by Xeio** [joakibj/tswcalc#48]
Opening an issue to track this and separate discussion from glyphs in #44.

I'd like to throw a mockup or two together for this at some point, since I'd rather move away from checkboxes for non-custom items.

I don't think any non-custom items were confirmed in the first NM NY kill, so this is still relatively low priority. If we get custom 10.6 glyphs working, then the MF:B dungeon drops probably aren't strictly necessary to implement (though I suppose they wouldn't be terrible to have).

**Comment by joakibj** [comment]
Agree that the checkboxes are not viable. Please check out #49 as well

**Comment by Xeio** [comment]
Sort of playing with a prototype for this functionality. Any thoughts? Not doing any sort of huge rewrite re-style at the moment. Just moving to be a bit more scalable.

Can view it here: http://tswcalc.azurewebsites.net/

Still buggy, layout issues, some boxes don't disable on import of custom items (though import does work). I think I may have also broken literally every unit test but I can worry about that later. :P

**Comment by joakibj** [comment]
Looks good. Could maybe rename the Role term to Item or something. Then change "DPS" to "Custom DPS" or something like that. Definitely more scalable when it comes to more raid drops etc.
