### ISSUE TITLE
Could Equal Footing Buff be added as a feature?

### ISSUE THREAD

**Issue by DJM-github** [joakibj/tswcalc#50]
Hey,

I would like to request a feature, were you could recalculate the stats with the Equal Footing buff.
Since many people play the new PVP area Shambala. Like I can only speak for me ... but I would
really love to know how to gear for PVP.

Here is a forum thread that shows how Equal Footing works:
[https://forums.thesecretworld.com/showthread.php?93938-Getting-the-most-ouf-of-Equal-Footing-Gearing-for-PvP&amp;goto=newpost](https://forums.thesecretworld.com/showthread.php?93938-Getting-the-most-ouf-of-Equal-Footing-Gearing-for-PvP&amp;goto=newpost)
... though I dont know if its up to date, but testing today looked like it still that way.

Also your Readme reads xD
> In addition to share and show others what gear you use to tackle encounters in PvE or **PvP**

PVP not really in tswcalc atm. Ofcause theres a lot to do with the new items from the nm raids but would be a "nice to have feature". (Oh and if there is that option already ... I'm a fool and you shall ignore this issue.)

Regards, DJM

**Comment by Inkraja** [comment]
My meaning: no

why?
equal footing is only for pvp and calculate the stats to a an equal amount than the group (normally max)
1: it depends on every glyph vs iteems and its hard to calculate
2: what should be the effort? the tswcalc was done for planing ur gear or share them to players, or not?

**Comment by DJM-github** [comment]
> 1: it depends on every glyph vs iteems and its hard to calculate

Ya you are right its not easy. Its just an Idea and I can understand if its to much work
Like I said, just a nice to have.

> 2: what should be the effort? the tswcalc was done for planing ur gear or share them to players, or not?

The idea is, thats ist easyer to plan your PVP gear with this feature, so you dont have to have max gear to overwrite Equal Footing, but instead can easily find out how one can gear cheaper to get the desired PVP stats.

**Comment by joakibj** [comment]
To be fair, non-item buffs and such are not the scope of tswcalc. Plus, this one scales according to stats. It would be possible to implement but pretty low priority compared to the other issues.

**Comment by joakibj** [comment]
Closed since this issue is not in the scope of tswcalc
