### ISSUE TITLE
Design Concept

### ISSUE THREAD

**Issue by Inkraja** [joakibj/tswcalc#54]
So i think a lot about a new concept and how to improve it, its still on working and still only a concept. 
But maybe it gives some new ideas

In the top u see the original and below the concept and the concept of the glyph menue

![tswcalc concept](https://cloud.githubusercontent.com/assets/10184036/13788238/556c71e8-eadf-11e5-9d32-8939834f70e5.jpg)

**Comment by Inkraja** [comment]
### Compare the space between "old" and "new"

![tswcalc_concept](https://cloud.githubusercontent.com/assets/10184036/13898623/a4562d44-edd7-11e5-8c2e-6c76b9d7bd16.jpg)

### Concept for different colors and select options
![tswcalc_concept2](https://cloud.githubusercontent.com/assets/10184036/13898624/a760eff6-edd7-11e5-9102-652c43b2de8e.jpg)

**Comment by joakibj** [comment]
Closing issues since Secret World Legends has a different gear system and is likely to replace TSW over time.

Thanks to everyone that has contributed to the project 👍
