### ISSUE TITLE
Distinguish epic item variations with different QL by name

### ISSUE THREAD

**Issue by joakibj** [joakibj/tswcalc#58]
New raid items introduce items in both epic and elite variations. These should be distinguishable by name when selecting them in the drop-downs.

For example: Item Name [Elite]

Can be hardcoded in the item datafile or made programmatically based on signet quality

Referring to #57

**Comment by Inkraja** [comment]
All raid items are epic, only Aegis stuff can be blue (Modules/Capacitors)
All MFB drops are epic, only the 10.8 items have 10.5 glyphs and blue signets, all 10.9 items are purple with purple signets and 11.0 glyphs.
NYR e.g. Subway tokes in 10.4 and 10.9 are both epic

So what do u mean with raid items in elite variations?

**Comment by joakibj** [comment]
Seems like there are some duplicate item entries, with both 10.8 and 10.9 QL. The only difference was signet quality so I assumed there were different tiers.

https://github.com/joakibj/tswcalc/blob/develop/src/javascript/data/tswcalc-data-items.js#L346
For example Anansi Chaos Generators, there are two entries. So in tswcalc it shows as a duplicate row in the drop-down. 

![tswcalc_58](https://cloud.githubusercontent.com/assets/3668627/14136201/d8eee0fe-f661-11e5-8160-03e25ee61ec3.png)

We need some way of distinguishing them. Not sure if the new item handling in tswcalc supports the same item with different glyph / signet values. @Xeio ?

**Comment by Inkraja** [comment]
yes the issue here is, that some items have different glyph stats (eg head bone powder). 
My real problem there is, that i have no idea is it a HP / heal or dps item, i think the double lines can be solved with adding the 10.8 or 10.9 information.

**Comment by joakibj** [comment]
Yeah I noticed, it is fine with double lines. Just that users should be able to know the difference at a glance.

Anansi Chaos Generators [10.8]
Anansi Chaos Generators [10.9]

Could work.

Do they drop from different dungeon difficulty levels?

Anansi Chaos Generators [Elite]
Anansi Chaos Generators [Nightmare]

Maybe ?

**Comment by Inkraja** [comment]
the first one is correct and better, they drops only in MF-B nightmare, in MF-B Elite the items drops are 10.5 elite (yeah they add 10.5 blue items...)

In MF-A nightmare the drops are 10.6 epic, but i didnt add them.

**Comment by joakibj** [comment]
Funcom why you do this :cry:

**Comment by Inkraja** [comment]
:laugh: i was searching some days before the items pics from the flappy and eidolon nm items in the media flash files....they "never" add new items, they used images they are still inside, to figured out where is my bracer of the ghoul king takes 4 hours, and iam still disappointed because i have no idea whats the images from the others... i only have an idea which items it can be.... :sad:
