### ISSUE TITLE
[Feature Request] - a phone/tablet Javascript-CSS3 modification

### ISSUE THREAD

**Issue by markstinson** [joakibj/tswcalc#60]
Greetings,

I'm not the best Javascript-CSS3 programmer out there (being a sysadmin), else I'd make the modification myself and submit a pull request.

Would it be possible to have a few float capabilities added to the Stylesheet so tswcalc become more phone and tablet friendly so when viewed on a mobile device, some page elements tuck into appropriate places to make the page more "narrow"? Here's a what I'm talking about:

![tswcalc phone-idea highlighted](https://cloud.githubusercontent.com/assets/92370/14453505/dd007146-005a-11e6-95db-7c8d8f6cbd46.png)
1. (Blue) I noticed the Item dropdown feels a little redundant. This could easily be remedied by placing it all on the same line.
2. (purple) Folding the global selectors for the QL10.x - 11 underneath DPS/Healer/Tank could fit nicely if centered.
3. (green) Folding the Glyph distribution underneath the glyph dropdowns still maintains/makes relationship sense.
4. (red) As the Summary stays on screen when scrolling down on the desktop, couldn't it have an icon to show it's like a pop-up menu on a narrow screen of a Phone or tablet? One could be working on their calculation, touch the "menu" to look at the current summary, then touching elsewhere the Summary menu hides and the selections re-appear.

Thanks in advance for your consideration. Cheers, Mark S.

**Comment by joakibj** [comment]
Should be doable with not much effort. tswcalc uses bootstrap which has builtin support for responsive layouts.

**Comment by joakibj** [comment]
Closing issues since Secret World Legends has a different gear system and is likely to replace TSW over time.

Thanks to everyone that has contributed to the project 👍
